### ISSUE TITLE
Reactive templates

### ISSUE THREAD

**Issue by davidmoshal** [olado/doT#104]
Hi, any thoughts on adding reactive templates and expressions, ala RactiveJS ??
Dave

**Comment by epoberezkin** [comment]
@davidmoshal if you mean two way binding with DOM (like angular, e.g.) it is definitely out of scope. Please reopen if the question is about something else.

**Comment by davidmoshal** [comment]
Hi, that question was 3 years ago! 
React and several other frameworks now implement this already, you guy missed that boat.
