### ISSUE TITLE
please don't clear blank

### ISSUE THREAD

**Issue by qidizi** [olado/doT#107]
the html like the:

doT.template('llll&lt;a\t\n\rhref="">blank&lt;/a>kkk') + '';

will echo 

"function anonymous(it) {
var out='llll&lt;ahref=" ">blank&lt;/a>kkk';return out;
}"

the "\t\n\r" will be clear,it is wrong;must be keep they.

**Comment by epoberezkin** [comment]
duplicate of #76, #177
