### ISSUE TITLE
Streaming friendly

### ISSUE THREAD

**Issue by cadorn** [olado/doT#114]
The readme mentions _streaming friendly_. I wonder what is meant by that and how to use it?

**Comment by rw3iss** [comment]
Also wondering if it's possible to pass the render output to a stream.

**Comment by epoberezkin** [comment]
"streaming friendly" is not the same as "returns a stream" :)
Templates return strings, any string is "streaming friendly".
There may be a value in making a streaming template, not sure if doT will ever be one.
Maybe it should be updated in docs somehow.
