### ISSUE TITLE
Injecting html market with it.get

### ISSUE THREAD

**Issue by ibmkaga** [olado/doT#118]
The value for one of the case has an html markup but whether i use the "encode" or simple "interpolation" its injecting that text as simple string and not respecting the markup in that text because of which the full markup comes as it is, without it being interpreted. e.g. if the string value is <img src="../img.png">, it comes as this text, instead of getting the image from the src attribute mentioned.

**Comment by epoberezkin** [comment]
@ibmkaga Please clarify the issue with some example.

**Comment by epoberezkin** [comment]
closing, please reopen if still relevant.
