### ISSUE TITLE
null-coalescing (“undefined” safe)

### ISSUE THREAD

**Issue by digeomel** [olado/doT#130]
Can you please add an option not to render null/undefined/false values by default?
The issue is explained better here:

http://stackoverflow.com/questions/9959842/is-there-a-javascript-html-template-that-supports-both-null-coalescing-undefin

Thanks in advance! :+1:

**Comment by ImUrX** [comment]
this repo seems very dead but js now supports a null coalescing operator (??)

**Comment by epoberezkin** [comment]
probably related to html encoding

**Comment by digeomel** [comment]
> probably related to html encoding

I'm not using dot anymore, since many years now (the question is from late 2014), but just out of curiosity, what do you mean? Doesn't my original link to stackoverflow illustrate the problem well enough?
I know that the latest JS supports the null coalescing operator, (i.e. `a?.b?.c`), is this what you mean? That now we can use this in dot.js?

**Comment by epoberezkin** [comment]
I see - thanks for the comment - no, I missed what you mean - it’s clear now.

It’s not supported.
