### ISSUE TITLE
How fast is do T tempalte comparing C, C++ tempalte engines?

### ISSUE THREAD

**Issue by topstarnetwork** [olado/doT#133]
Hello, 
How fast is do T tempalte comparing C, C++ tempalte engines?
I was hesitating with do T and any c c++ template engine for high speed and cpu performance.for my php website.
Would you have any info about that?
I was hesitating using do T  or any of the  c or c++ template engines wich are said to be  the fastest such as those once;

http://alexeyrybak.com/blitz/blitz_en.html or http://en.wikipedia.org/wiki/CTPP for php websites,
http://www.clearsilver.net/
http://teng.sourceforge.net/

**Comment by Fudoshiki** [comment]
compiled templates with doT returned on my localhost for 1ms, fastest result what I seen

**Comment by epoberezkin** [comment]
@topstarnetwork I believe it is answered, please reopen otherwise
