### ISSUE TITLE
"{{" without whitespace after is not treated as code

### ISSUE THREAD

**Issue by adamrogas** [olado/doT#135]
The issue is that when you strip whitespace on a file that has line style comments 

i.e. //commnted text

the comments will almost always cause unintended side effects, like client side javascript errors

**Comment by glukki** [comment]
Block comments FTW!
`/* whatever */`

**Comment by ouadi** [comment]
The above solution doesn't work when `dot.templateSettings.strip` is set to `true`.

The code:
```javascript
dot.templateSettings.strip			= true;
dot.templateSettings.append			= false;
dot.templateSettings.selfcontained	= false;
var template = '' +
	'{{/* Some comment*/}}\n' +
	'Hello\n' +
	';';
var compiled = dot.template(template, undefined, {});
console.log(compiled({}));
```

produces:

```
{{}}Hello
```

Note: I have posted this same comment on #165.

**Comment by epoberezkin** [comment]
You need to use `{{ /* Some comment*/ }}`. There may be a place for doT comments that are not included in the compiled function, although I am not sure about the value of such feature.

Probably adding to doT 101 is a good idea #205
