### ISSUE TITLE
loadfile not working 

### ISSUE THREAD

**Issue by kirkstrobeck** [olado/doT#136]
Using `{{#def.loadfile('/snippet.txt')}}` returns

    TypeError: Object #<Object> has no method 'loadfile'

**Comment by OGrape** [comment]
Hey I have the same problem here.

**Comment by olado** [comment]
def.loadfile is an example. It is defined in https://github.com/olado/doT/blob/master/examples/withdoT.js#L7 and is only meant to illustrate to you can invoke custom functions with def.
It works if you run the example: node withdoT.js
