### ISSUE TITLE
Passing data to def function

### ISSUE THREAD

**Issue by OGrape** [olado/doT#137]
I have problem accessing the data in the def function.
Just for an example, I have a data of 
~~~
{"name":"Jake","age":31}
~~~
And here's a template file
~~~
{{##def.test = function(str) {
     return "My name is: " + str;
}
#}}
{{#def.test(name)}}
~~~
As I tested the result will print out "My name is:" instead of "My name is Jake".
Is there a way to passing data to def function?

something like this???:
~~~
{{#def.test("{{=it.name}}")}}
~~~
or
~~~
{{#def.test(it.name)}}
~~~

**Comment by olado** [comment]
Def functions are invoked right away. 
If you want to use def functions and pass values from your it data you can do:
option 1 : 
     {{##def.mytestparam: {{=it.name}} #}}
     {{#def.test(def.mytestparam)}}
option 2: 
     {{#def.test("\{\{=it.name\}\}")}}

You can also use parameterized def instead of a function in this case like this:
{{##def.test:myparam:
      My name is: {{=myparam}}
#}}

{{#def.test:it.name}}

**Comment by maxiruani** [comment]
I can't get it working.
Option 1 has and unexpected behaviour: The string "{{=it.name}}" not evaluated is passed to test function.
Option 2 gives me: "Unexpected token ILLEGAL".

There is another option?

**Comment by olado** [comment]
@maxiruani @OGrape I added an example here https://github.com/olado/doT/commit/195025f06055761f6da3a900251382e788c42d0e
You can pull this and run node withdoT.js to see that all 3 options work.

**Comment by maxiruani** [comment]
I can see now where is my problem.
First, it can't be defined inside another {{##def.block}}
Then, I was trying to evaluate nested def functions like this.

```javascript
{{##def.mytestparam: {{=it.value}} #}}
{{#def.functionOne(def.functionTwo(def.mytestparam))}}
```
The string "{{=it.jobsCount}}" is passed to functionTwo instead of the evaluated string.

This works
```javascript
{{#def.functionOne("\{\{=it.value\}\}")}}
```

This doesn't
```javascript
{{#def.functionOne(def.functionTwo("\{\{=it.value\}\}"))}}
```

Any ideas?

Thanks a lot!
