### ISSUE TITLE
Load template files asynchronously.

### ISSUE THREAD

**Issue by fabienbrooke** [olado/doT#139]
Please change the `readdata` method to use `fs.readFile` rather than `fs.readFileSync` so that the module can be used inside web servers.

**Comment by glukki** [comment]
Isn't it better to read all templates on server initialisation stage?

**Comment by fsbdev** [comment]
To be more specific, I mean inside web request handlers.

**Comment by epoberezkin** [comment]
@glukki doT isn't supposed to be used like this. The recommended approach is to pre-compile all templates during app initialisation (or even in build step) in which case synchronous is better.

Even if you have a really large number of templates and you want to lazy load them only when they are used (I can't see where this will be a case though) you always can write your own loader and use dot.compile with strings.
