### ISSUE TITLE
Templates in separate file for browser/client side

### ISSUE THREAD

**Issue by narendra-agashe** [olado/doT#140]
I have script tags on my index.html page as templates and they are being referred in my JavaScript code and all works fine. if I try to move script tag in a separate file everything stops working. could you please show me how templates works with separate files. I might have misinterpreted the documentation.

i tried loading the file using script tag with src attribute, also tried to load it through JavaScript function nothing seems to work.

Regards,
Naren

**Comment by epoberezkin** [comment]
@narendra-agashe I think it is not the question about doT, it is more about structuring your JS code in general. Please submit to StackOverflow.
