### ISSUE TITLE
tag 1.0.3 in gitHub so we can use it in bower!

### ISSUE THREAD

**Issue by timomayer** [olado/doT#141]
can you pls do that? latest version on gitHub is 1.0.1

**Comment by mistic100** [comment]
bump

**Comment by epoberezkin** [comment]
added

**Comment by mistic100** [comment]
Finally someone is taking over the project ? That's great !
I wrote messages to @olado to do it myself a bunch of times be never got any answer.

**Comment by epoberezkin** [comment]
@mistic100 yes, I am going to look after it.
