### ISSUE TITLE
can't tell where json object begins and where interpolations begins.

### ISSUE THREAD

**Issue by cfurst** [olado/doT#147]
Template:

``` javascript
{{? (Object.keys(it))[0] }}
{
{{ for (key in it) { }}
"{{= key }}":"{{ it[key] }}"
{{ } }}
}
{{ ? }}
```

does not compile..

will produce
if ((Object.keys(it))[0]) {{ ... }

**Comment by zlumer** [comment]
You have 2 syntax errors here:
1. `{{ it[key] }}` should be prefixed with `=`: `{{= it[key] }}`
2. `{{ ? }}` should have no space on the left: `{{?}}`
This code works:
```
{{? (Object.keys(it))[0] }}
{
{{ for (key in it) { }}
"{{= key }}":"{{= it[key] }}"
{{ } }}
}
{{?}}
```

**Comment by zlumer** [comment]
On a side note, why whould you want to write it manually?
`{{= JSON.stringify(it) }}` works perfectly.

**Comment by cfurst** [comment]
No space on the left? Does that also apply to {{~}}??
Very interesting. Something I was doing was producing the following when the template was parsed:
```javascript
if (expression) {{ <-- with the two brackets because the interpreter was taking on an extra bracket.
```
and it looked like this expression was producing it:
```javascript
{
{{? expression }}
```
I'll see if I can produce a better example.

**Comment by cfurst** [comment]
Found it!!
```javascript
{{? it[key][0] }}
{
	{{ console.log("key: " + key); }}
{{?}}
```
produces:
```javascript
if(it[key][0]){{ console.log("key: " + key); <-- with the double brackets
``` 
This should be...
```javascript
if(it[key]){out+='{';console.log("key:" + key); 
```

**Comment by epoberezkin** [comment]
@cfurst it looks resolved to me: https://runkit.com/esp/58167b4d221a5e0014ddfcd2
