### ISSUE TITLE
require templates question

### ISSUE THREAD

**Issue by Fudoshiki** [olado/doT#149]
Hello, I used express example and this work pretty good, but i want clean my code with manual example

inside project folder
$ node

> var dots = require("dot").process({path: "./templates"});
> Compiling all doT templates...
> Loaded def login.def.jst
> Compiling dashboard.jst to file
> Compiling login.def.jst to file
> undefined
> console.log(dots)
> {}
> undefined

and this return undefined

**Comment by epoberezkin** [comment]
@Fudoshiki are there templates in your folder? .process does not support subfolders
Please close if you've found the problem
