### ISSUE TITLE
Array iteration and HTML table only displays last array element

### ISSUE THREAD

**Issue by stiana** [olado/doT#151]
Hi,

I've tried to use a `<table>` together with array iteration, but I only get the last array element displayed. (Tested in Chrome V41.0.2272.101) and IE11 on a Win7.

If I remove the `<table>`-tags and just try to do a {{!value.Name}} `<BR>`, it works fine.

Funny thing is that I've pasted the same tamplate and data into the "Try it yourself" on http://olado.github.io/doT/index.html and it works fine. 

To make sure I had the latest version of the DoT.js, I tested with the same DoT.js directly from the http://olado.github.io/doT/index.html-page, but there was no difference.

I would like to add that I have tested to supply the data both statically and from a socket. (Client side)

Here's the template and data i've tested with.

Template:
```html
<div id="testdiv">
  <table border="1">
    <thead>
      <tr>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
{{~it.vars: value}}
      <tr>
        <td>{{!value.Name}}</td>
      </tr>
{{~}}
    </tbody>
  </table>
</div>
```

Data:
```javascript
var TemplateData = { "vars":
  [
    {"VID":29,"Name":"Scheduler Aktiv Gang","LogInterval":1,"LogType":1,"PLCVariable":"P_Controller.fbRoom[2].fbOptimizedPeriod.bOutput","Datatype":1,"Legend":"0"},
    {"VID":33,"Name":"Scheduler Aktiv Gang (Non Optimized)","LogInterval":1,"LogType":1,"PLCVariable":"P_Controller.fbRoom[2].fbOptimizedPeriod.bOutputNonOptimized","Datatype":1,"Legend":"0"},
    {"VID":26,"Name":"Scheduler Aktiv Kontor","LogInterval":1,"LogType":1,"PLCVariable":"P_Controller.fbRoom[1].fbOptimizedPeriod.bOutput","Datatype":1,"Legend":"0"},
    {"VID":27,"Name":"Scheduler Aktiv Kontor (Non Optimized)","LogInterval":1,"LogType":1,"PLCVariable":"P_Controller.fbRoom[1].fbOptimizedPeriod.bOutputNonOptimized","Datatype":1,"Legend":"0"}
  ]
}
```

DoT-code:
```javascript
var mydiv = document.getElementById('testdiv');
var pagefn = doT.template(mydiv.innerHTML);
mydiv.innerHTML = pagefn(TemplateData);		

```

**Comment by zlumer** [comment]
@stiana from your code it seems that you're embedding doT templates into your HTML. That will most certainly break DOM parser in your browser.
If you want to embed templates into HTML, surround them with `<script>` tags with `type` attribute set to something you'd like (not `text/javascript`).
Working example here: http://jsfiddle.net/8ryovycw/

**Comment by stiana** [comment]
Thanks a lot, @zlumer. Makes sense to me now :+1:
