### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by signumcode** [olado/doT#153]
line 94 in dot.js:  str = ("var out='" + (c.strip ? str.replace(/(^|\r|\n)\t\* +| +\t*(\r|\n|$)/g," ")
can you change the last white space " " to "" ?

**Comment by btpoe** [comment]
If you wrote the following HTML:
```
<p>Hello
World</p>
```
It should compile to: `<p>Hello World</p>`. Your suggested change would compile to: `<p>HelloWorld</p>`.

**Comment by epoberezkin** [comment]
@signumcode closing it.
related to #76
