### ISSUE TITLE
Can I nest two {{= }} ? 

### ISSUE THREAD

**Issue by qijiqiguai** [olado/doT#154]
Like 
value="{{=moment( {{=it.val}} ).format('YYYY/MM/DD') }}"

**Comment by zlumer** [comment]
Probably `value="{{=moment(it.val).format('YYYY/MM/DD') }}"` can work in this case.

**Comment by qijiqiguai** [comment]
@zlumer It's worked, even easier then i expected! thanks a lot :-) 
:+1: 
:100:
