### ISSUE TITLE
Just a suggestion: Can I Write Some Comment Use doT?

### ISSUE THREAD

**Issue by chenjihu** [olado/doT#165]
As the title.  e.g.  {{//this is the comment}} , but it won't be rendered to the browser, which just for developer reading.

**Comment by btpoe** [comment]
You can write `{{/* This is a comment */}}`

**Comment by ouadi** [comment]
The above solution doesn't work when `dot.templateSettings.strip` is set to `true`.

The code:
```javascript
dot.templateSettings.strip			= true;
dot.templateSettings.append			= false;
dot.templateSettings.selfcontained	= false;
var template = '' +
	'{{/* Some comment*/}}\n' +
	'Hello\n' +
	';';
var compiled = dot.template(template, undefined, {});
console.log(compiled({}));
```

produces:

```
{{}}Hello
```

**Comment by epoberezkin** [comment]
duplicate of #135, see answer there.
