### ISSUE TITLE
Undefined using {{#def.

### ISSUE THREAD

**Issue by gahula** [olado/doT#166]
var doT             = require("dot").process({path: './views'});

app.engine('html', consolidate.dot);
app.set('view engine', 'html');
app.set('views', __dirname + '/views');

/render html
res.render('map/index-view.html', context);

//folder hierarchy
views
---map
-------index-view.html (has {{#def.nav #}} inside)
---people
---places
layout.def (has {{##def.nav:TEST #}} inside) 

//Error received
getting undefined when {{#def.nav #}} is called inside index-view.html

**Comment by epoberezkin** [comment]
@gahula you can use `doT.process` without consolidate.dot, it won't work like this (you are not using doT variable as you can see).
Also I need to check if `doT.process` supports subfolders, I don't think it does.
You can use express-dot instead.
