### ISSUE TITLE
Pass a variable to a REUSABLE method?

### ISSUE THREAD

**Issue by gahula** [olado/doT#167]
{{~ model.array :item}}
    <tr>
        <td>{{ .reusableMethod(item.param, 'string to pass', model.array) }}</td>
    </tr>
{{~}}

Where would I define methods that will be used often ?
How do you pass array values and even the array itself to the function ?

**Comment by btpoe** [comment]
```javascript
{{ function subTemplate(foo) { var out = ''; }}
    <div>{{= foo }}</div>
{{ return out; } }}
{{= subTemplate('bar') }}
```
weird? yes.
works? yes.

**Comment by gahula** [comment]
No, that is not sustainable.

I meant reusable in terms of it being used by other pages throughout the app. I guess the way to do it is to pass the function.

//Helpers.js - a file which contains reusable functions
var helpers = require('helpers');

//Pass function to page
var context = {
       reusableFunction: helpers.reusableFunction
};

res.render('/pagedot', context);
