### ISSUE TITLE
The `encodeHTML` code shouldn't make numeric zero turn into the empty string

### ISSUE THREAD

**Issue by Pointy** [olado/doT#170]
The HTML encoder checks it's input argument for truthiness before attempting the actual encoding. If that test fails, the return value is the empty string. That's probably fine for `null` and `undefined`, but it's somewhat disturbing that numeric `0` (and, now that I think of it, `NaN`) is converted to the empty string. To ensure that the "number fix" from a few months ago keeps working properly, it'd probably be good to include an explicit test for numbers:

```
return (code || typeof code === "number") ? code.toString().replace(...) : "";
```

**Comment by Pointy** [comment]
I guess some people might think it's weird for `false` to end up as the empty string too.

**Comment by crzidea** [comment]
Agree. I have exact same issue with numeric. I will take a PR on this.

**Comment by epoberezkin** [comment]
custom encoders in 2.0, can be configured as needed
