### ISSUE TITLE
provide hooks(placeholder) or helper method for mixining template

### ISSUE THREAD

**Issue by icai** [olado/doT#172]
My idea is that the `view` method in backbone or other mv\* framework can Mixin by several component, the template is difficult to  mixin template.

main template

```
<div class="feed-list-item">
    <h2 class="sr-only">{{=it.user.display_name}} submitted the post on {{=it.display_ctime}}</h2>  
    <# subtemplate #>
</div>
```
---

<# subtemplate #>

```
<a href="{{=it.url}}" target="_blank" class="task-url" >Go to Task</a>
```

on render method, I can mixin the template first (just use replace), how ever if I don't mixin this. do.template would hlep me remove this hook(placeholder)(<# subtemplate #>) in main template.
---

You may say that you can use conditional logic in template. Obviously you know the component would be not complete(lose the template).

maintemplate = maintemplate.replace('<# subtemplate #>', subtemplate);

before I do `dot.template(maintemplate)`, `dot.template` would `clean` the hooks(placeholder) if have.

**Comment by epoberezkin** [comment]
doT supports macros ( `{{##def.something: ... #}}` ) and you can pass helpers methods in template in three ways:

- as data properties
- as context properties (using .call/.apply) #175
- as function parameters (by modifying templateSettings.varname, see https://github.com/olado/doT/issues/92#issuecomment-24780234)
