### ISSUE TITLE
Support vdom output (react or others).

### ISSUE THREAD

**Issue by DylanPiercey** [olado/doT#173]
Instead of compiling into a string creating function it would be awesome if doT could also compile into a react compatible vdom or even just JSX (which would be compiled again).

Currently the only other templating language for react is Jade, it would be nice to see some competition.

Thoughts?

**Comment by noomorph** [comment]
Did you check this? https://github.com/wix/react-templates

**Comment by DylanPiercey** [comment]
@noomorph Thanks for the link! Certainly a cool little project.

I am hoping to see the larger template languages compete such as doT and ejs in this area.

**Comment by epoberezkin** [comment]
@DylanPiercey seems out of scope.
Although doT for react could give it some traction maybe :)

**Comment by DylanPiercey** [comment]
@epoberezkin this was posted a long time ago. I think nowadays the best and simplest solution is to use [set-dom](https://github.com/DylanPiercey/set-dom) or [morphdom](https://github.com/patrick-steele-idem/morphdom).
