### ISSUE TITLE
Feature request: allow partial modification of templateSettings

### ISSUE THREAD

**Issue by garann** [olado/doT#174]
I just ran into an issue where I was trying to change `templateSettings.varname` and as  result my templates weren't being compiled. Looking at the code, I realized that by changing only one attribute of the config object, I was wiping out all the others. 

Though not crucial, it would be nice to be able to change individual config attributes without having to maintain a copy of all the others, for example in case of an update that adds a new attribute that older user code might not contain. 

I had two possiblities I'd considered for doing this, but am unsure if either matches the project's intentions. If either does, I am happy to create PRs. They are:
- in `doT.template`, loop through any attributes in `c` and overwrite those in `templateSettings`
- add a function to alter `templateSettings` at the object level before use so it doesn't impact the speed of `doT.template`

**Comment by ScrippsFEE** [comment]
+1 for the 2nd option: add a method to alter templateSettings.

**Comment by epoberezkin** [comment]
You already can change individual options on the package level by assigning to individual properties of templateSettings, so adding a method is not necessary strictly speaking.
So I think dot.template should be changed, as it would allow to change options only for the current template
Another common problem is changing interpolation syntax (e.g. to <%...%>) for all instructions - there can be a method to achieve just that. It would be useful to use templating both on server and client side (e.g. with Angular).

**Comment by epoberezkin** [comment]
#51 addresses it but it needs changes

**Comment by epoberezkin** [comment]
With ES2018 you can just {...doT.templateSettings, <your options>} which is quite idiomatic and does not require any changes...
