### ISSUE TITLE
Interpolation in an interpolated string?

### ISSUE THREAD

**Issue by thomaslindstrom** [olado/doT#176]
Is there a way to re evaluate an interpolated string because it too has interpolation?

it.string:
```
Hello, {{=it.name}}!
```

output.dot:
```
{{=it.string}}
```

Current result:
```
Hello, {{=it.name}}!
```

What I want is:
```
Hello, Peter!
```

Is there some function I could create that kind of recursively does this?

**Comment by zlumer** [comment]
I'm almost ceratin that you're looking for partials.
However, if you really need that kind of recursive interpolation, feel free to call doT directly from your template:

```
Hello, {{= doT.template(it.string)(it) }}
```

**Comment by thomaslindstrom** [comment]
Thanks! I gave up trying to make it work with partials. But your suggestion works like a charm!
