### ISSUE TITLE
Conditionals and logical operators.

### ISSUE THREAD

**Issue by coldlamper** [olado/doT#186]
Can you use conditions with logical operators like

```
{{? it.var1 && it.var }}
    Var1: {{= it.var1 }} Var2: {{= it.var2 }}
{{?}}
```

I've tried but it doesn't seem to work.

**Comment by epoberezkin** [comment]
@coldlamper Conditionals can be used with any JS expression.

Please define "doesn't work". Template doesn't compile? It produces unexpected result? If the latter, maybe the issue is that you use `it.var` and not `it.var2` in conditional?
