### ISSUE TITLE
Feature request: use promises/deferred for long operations

### ISSUE THREAD

**Issue by digeomel** [olado/doT#187]
I would like to have a way to know when a lengthy fill-in of a template has finished. Ideally this should be done with promises.
You might be asking yourself, what kind of template do I have that takes so long to fill in? And the answer to that is a template which can be loaded with html containing inline base64-encoded images :smile: 

:bow: thanks!

**Comment by zlumer** [comment]
doT template processing is not async, why would you need promises?

**Comment by digeomel** [comment]
Well, maybe it should be, I explained my problem above, some templates can take more than 3 seconds to display in the browser, I'd like the user to know that something is going on.

**Comment by zlumer** [comment]
Unfortunately, async rendering in browsers is (practically) not possible.
If you would like the user to know what's going on, you can do it the usual way:
1. Display the 'loading' pic/message.
2. Start rendering template.
3. Remove 'loading' pic/message.

If the message does not appear until rendering is finished, just delay it with `setTimeout()`, e.g.:
```js
$('#loading').show(); // show loading message
setTimeout(go, 50); // delay template rendering by 50 ms
function go()
{
  render({}); // actually render the template with doT
  $('#loading').hide(); // remove loading message
}
```

**Comment by digeomel** [comment]
I was hoping to avoid this, but I guess there's no other way out. Thanks anyway! :smile:

**Comment by epoberezkin** [comment]
Closing. Seems out of scope.
