### ISSUE TITLE
Log printing

### ISSUE THREAD

**Issue by robjens** [olado/doT#188]
As far as I can tell, there is no option to disable the (verbose) printing of the console message including/after:

`Compiling all doT templates...`

Currently, I'm almost forced to catch all stdout/console output just to get rid of it. To be fair, I am not sure what the prefered solution would be though, I recon the cleanest, easiest and most common solution would be to make this simply an option to pass on/off printing - or another would be to accept an object/method as log handler.

But as it is now, and using a machine friendly logger (bunyan) to JSON, this is throwing sand in the bearings and although it is mostly an aesthetic uniformity issue, not many packages I use take the liberty (the audacity I might even say) to pollute my screen and don't allow it to be turned off. (I did check the source, couldn't find it).

If it isn't possible/desirable to fix this, I'm going to have to fork this project but I rather first try it this way and see if there is any agreement on this or perhaps even, I'm overlooking the switch I hope.

**Comment by houd1ni** [comment]
feel free to reopen https://github.com/olado/doT/issues/191

**Comment by robjens** [comment]
Ok thanks, I'll close this anyway regardless if I'll do that ;)
