### ISSUE TITLE
Return null or undefined, not string containing the text "null" or "undefined"

### ISSUE THREAD

**Issue by nekobul** [olado/doT#190]
Is this possible?

**Comment by nekobul** [comment]
The script can be easily made to return the raw value, not the converted to string value. I propose the following line to be modified from:

.replace(/(\s|;|\}|^|\{)out\+='';/g, '$1').replace(/\+''/g, "");

to:

.replace(/(\s|;|\}|^|\{)out\+='';/g, '$1').replace(/\+''/g, "").replace(/''\+/g, "");

**Comment by houd1ni** [comment]
feel free to reopen https://github.com/olado/doT/issues/191

**Comment by epoberezkin** [comment]
@nekobul can you please clarify the issue

**Comment by nekobul** [comment]
Hi Evgeny. I have provided description of the issue above. What is not clear?

**Comment by epoberezkin** [comment]
> Return null or undefined, not string containing the text "null" or "undefined"

It doesn't say in which case you want it to happen. What is the template, what is the data you pass to it, what is the current and expected result.

> The script can be easily made to return the raw value, not the converted to string value.

which script are you referring to?

**Comment by nekobul** [comment]
Let's say you have object: var hello = { prop1: "10", prop: "20" };

If you pass the object to the template as : "{{=hello}}", I want to get the actual object, not the text "[object]".

**Comment by epoberezkin** [comment]
Template function is supposed to always return strings, not any other data. If you want a stringified object you need to use JSON.stringify:

```
{{= JSON.stringify(it) }}
```

**Comment by nekobul** [comment]
Evgeny, I don't want stringified object. I want the actual JS object.

And who says the template function should always return strings? If it is possible to return objects, why not have it as a feature? doT can be very useful as object/property selector type of engine.

**Comment by epoberezkin** [comment]
@nekobul templating is about taking data and converting it to a string.

I am not sure I understand your use case, it seems highly uncommon. In all real use cases the template would have some text before and after interpolation, that's why the result will be a string.

If your template has nothing but interpolation I don't think I understand what is the reason to have it inside a template at all. Can you explain your use case?

**Comment by nekobul** [comment]
I'm using JS engine which combines user definitions which use doT template strings. The result strings/objects are integrated with the .NET framework where sometimes strings are fine but some times the actual JS objects are needed.

**Comment by epoberezkin** [comment]
ok. I still don't understand why you need to use templates that have nothing but interpolation when you could use actual expressions. Or you are letting your users to write template strings and do actual code injection?

**Comment by silkster** [comment]
> Let's say you have object: var hello = { prop1: "10", prop: "20" };

> If you pass the object to the template as : "{{=hello}}", I want to get the actual object, not the text "[object]".

@nekobul, this doesn't make sense to me, either. It sounds like you need to wrap doT with a function that can return either the doT result or something else depending on whatever logic you need.

**Comment by nekobul** [comment]
Evgeny, that's precisely the case . The template strings are user-defined and depending on the situation I have to process either a string or the actual interpolated object or property.

**Comment by epoberezkin** [comment]
@nekobul I understand. I'd say it's a major security concern. No changes are necessary in doT though. Thank you.

**Comment by nekobul** [comment]
Hi Silk, not making sense to you doesn't necessarily mean it is not a valid feature. The code change I propose is very simple and wouldn't break existing implementations I believe.

**Comment by nekobul** [comment]
Evgeny, I have proposed code change in doT above. Please review.

**Comment by epoberezkin** [comment]
I understand. This change will not be made. Your use case is out of scope of what doT should be doing. Sorry.

**Comment by nekobul** [comment]
Evgeny,

What is the security issue you see with the change I have proposed?

**Comment by epoberezkin** [comment]
The security issue is to allow users write code that is injected in your app via templating. Nothing prevents me from writing `process.exit(1)` there. For doT this change is wrong as templating functions should always return strings.

**Comment by epoberezkin** [comment]
https://www.xkcd.com/327/

**Comment by nekobul** [comment]
Evgeny, you understand perfectly well I can modify doT script code at runtime using other JS code, making it do whatever I want. I don't think your argument has too much merit and I  hope you reconsider.

**Comment by silkster** [comment]
That was my point. Just make a freakin wrapper that does what you want. Your request is out of scope.

**Comment by nekobul** [comment]
Hey silk, why not close the project entirely for new ideas and tell everybody it is all out of scope? I thought we are both here to make the project better.

**Comment by silkster** [comment]
There's nothing stopping you from branching and making your own changes.

**Comment by epoberezkin** [comment]
@nekobul I am sorry but you would have to respect refusals. Doing open source development is hard enough, so it's important to stay polite even if the changes you believe are absolutely necessary and vitally important are not seen as such by the community around the project. I've been in this position many times, it's not a problem really. As @silkster wrote, forking and making any changes you want is always an option.

**Comment by nekobul** [comment]
Evgeny, you are the one who started with the jokes without knowing who I am or what is my experience. Yes, I agree it is important to stay polite, but respect is two way street. I'm not exactly sure what kind of moderator you are when my original post was dated Apr 20th, 2016. It took you more than 6 months to respond to my question. I understand this is open-source project and there are no guarantees, but still it makes you wonder if you care enough about the project.

I still believe the change I have proposed made sense. Still, it is up to you as moderator to decide.

**Comment by epoberezkin** [comment]
Sorry about the jokes. I have started maintaining doT about a week ago, trying to get the feedback to the opened issues. That's the reason for delay.

**Comment by silkster** [comment]
@epoberezkin, I'm happy to see someone finally maintaining this project. Thank you!

@nekobul, there is a fork of this project at https://github.com/houd1ni/doT started a while back because of the lack of moderation here. It's maintained by @houd1ni. You could try suggesting the same change there.

**Comment by houd1ni** [comment]
@silkster  Even if the branch would maintaining as a kinda modification after master had been picked up, I couldn't accept the actual PR due to the same reason: I cannot see any sense of template engine, that executes any user code.

But I can suggest to @nekobul  to provide someway to connect plugins to the library and make it easy to wrap anything that you want easily and publish it or make some parser for whitelisted data signatures.
```I.e. {name: 'Thomas', job: 'smileshiner'} =>
  <p>name:  Thomas</p>
  <p>job: smileshiner</p>
```
But it is obvious that one would be interested in changing this `special` markup, so you also at least have to offer some option to easily provide an algorithm that searches for special objects and turns them into strings to be safely parsed.

@epoberezkin  What do you think? Could It be a low-priority but real improvement?

**Comment by nekobul** [comment]
The templating engine can execute user code even now. What I'm suggesting is to not explicitly convert the result of the interpolation to a string. That's all.

**Comment by houd1ni** [comment]
@nekobul  The engine calls SomeObject.toString() method anywhere as I now it.
What other transformation can be common and cannot confuse most of our colleagues?

**Comment by nekobul** [comment]
houd, that's not the case. Debug the engine code and you will see what is happening.
