### ISSUE TITLE
Variables from template

### ISSUE THREAD

**Issue by dellert** [olado/doT#192]
Can I get variable from template? I need to save changed data from my templates, so how can I get it? 
Something like this
`doT.template($('#tmpl_inline).html()).getIt()`

**Comment by ScrippsFEE** [comment]
Templates are stateless. Instead, compare the data used to create the markup from the template to the data after the user has interacted with it.

**Comment by dellert** [comment]
@ScrippsFEE Thanks, but how I can compare the datas in this context?

**Comment by ScrippsFEE** [comment]
The template just renders the HTML. If the HTML has an input field, for example, you get the value of the input field from the DOM after the user enters a value. 

I don't know what your data looks like, but say your template looks like this: 

`<input id="username" value="{{=it.username}}" />`

and the data to create the template looks like this: 

```
myData = {
    "username": "dellert"
};
```

Then you just compare them like this:

```
if (myData.username == document.getElementById('username').value) {
    // do something
}
```

**Comment by dellert** [comment]
@ScrippsFEE Thanks
