### ISSUE TITLE
reformat code brings bug

### ISSUE THREAD

**Issue by dukegod** [olado/doT#194]
<script id="template" type="text/x-dot-template">
      <p>
        <span>cancel</span><span>confirm</span>
      </p>
    </script>
    
    <script id="template2" type="text/x-dot-template">
      <p>
        <span>cancel</span>
        <span>confirm</span>
      </p>
    </script>

they should show me the same result. but in the second template, after rendering, there is 'space' between 'cancel' and 'confirm'. 

[ref img](http://7xsubf.com2.z0.glb.clouddn.com/2016-04-11%2011.20.33.png)

**Comment by ScrippsFEE** [comment]
<span> tags are inline elements so when the line break will effectively act as a space. If you don't want them to have a space between them, then you should float them both with CSS.
