### ISSUE TITLE
How to pass object to partial in dot.js

### ISSUE THREAD

**Issue by Aure77** [olado/doT#195]
How can I pass multiple parameters ou JSON object to a partial using dot.js ? cf. http://stackoverflow.com/questions/36726523/how-to-pass-object-to-partial-in-dot-js

Is it a bug or I am missing something ?

**Comment by epoberezkin** [comment]
@Aure77 the question is answered in SO I believe. 
I believe #110 tries to improve it, but it's out of date and need changes.
