### ISSUE TITLE
Any take on ES6?

### ISSUE THREAD

**Issue by jimmywarting** [olado/doT#197]
Thinking ES6 template string. Also wonder if some other stuff can be of more performance like `for...of` block variable `let` among other things

**Comment by epoberezkin** [comment]
@jimmywarting what is the purpose of using template strings here? `let` usually has worse performance than `var`, so what's the point to use it here?

**Comment by jimmywarting** [comment]
Not really sure why i want it. The compiled source is smaller with template strings, fat arrow and för..of, looks cleaner too.

**Comment by epoberezkin** [comment]
@jimmywarting ah, you meant compiling to es6, not using es6 in doT itself? You obviously can use es6 in your code inside `{{ }}` if your environment supports it. Using template strings/for..of can make it shorter indeed...

**Comment by jimmywarting** [comment]
yea, I mostly meant compiling to es6 but using it in doT itself would be nice too

**Comment by jbmonroe** [comment]
@epoberezkin 'let' vs 'var' : scoping. Sometimes being able to reason about what the code does overrides potential performance issues.  Over time the engines will get better with it, anyway.

**Comment by epoberezkin** [comment]
@jimmywarting I am going to close the issue, it feels somewhat out of scope here. Introducing es6 into doT itself would mean the need to transpile code, which I am not a big fan of doing in libraries... 

Generating code as es6 template strings can be an interesting option. Without making any promises, if you make a fork that does it with some option and the code size increase is <10-15% (which is possible) I would probably merge it into 2.0.0. If the code size increase is substantial, then it can exist as a separate package dot-es6 (in which case doT itself could use es6).
