### ISSUE TITLE
Unable to compile this plain HTML snippet!

### ISSUE THREAD

**Issue by enormouspenguin** [olado/doT#198]
I use the demo on http://olado.github.io/ to compile [this very long pure HTML](http://pastebin.com/DDVWeHtV) taken straight from a webpage [here](https://www.drupal.org/node/313510)  but the result is a javascript function full of syntax errors when running. Can doT.js handle long HTML?

**Comment by zlumer** [comment]
doT compiles and runs fine for me with this HTML.
What errors do you get?

**Comment by enormouspenguin** [comment]
When I copy the generated js code in the "doT.template compiles it into" and try to run it, I got 49 errors and 2 warnings with [this JSbin snippet](http://jsbin.com/resejovoqa/edit?html,css,js,output) and some cryptic error message with Chrome's developer console: 

> Uncaught SyntaxError: Unexpected identifier(…) VM265:2 
> InjectedScript._evaluateOn @ VM96:878
> InjectedScript._evaluateAndWrap @ VM96:811
> InjectedScript.evaluate @ VM96:667

I use Chrome Version 49.0.2623.87.

Just to be sure, [here](http://pastebin.com/8ESqVDuv)'s the js content of my clipboard that I pasted on both JSbin and Chrome.

**Comment by zlumer** [comment]
Ok, now I see the error.
It's not a problem with doT itself, it's a limitation of the playground. The resulting function code is inserted into a DIV and HTML markup is broken.

However, if you run the code from your browser console (F12 in Chrome), you'll get correct result:
http://pastebin.com/NBDSKk4G

**Comment by enormouspenguin** [comment]
Phew, what a relieve! My team is evaluating doT.js for our project and this hiccup appeared right at the first try. Luckily enough, it turns out to be just a tiny unrelated problem.

Still, could this easily be fixed by escaping before printing, using one of the methods suggested in [this](http://stackoverflow.com/questions/24816/escaping-html-strings-with-jquery)? Can I do anything to help?

**Comment by zlumer** [comment]
This DIV on the site is used for illustration purposes. It's not meant to use for direct testing.

If you want to copy the resulting function source, run the following command in your console after pasting the template code:
```js
doT.template($('.template')[0].value, undefined, {});
```

**Comment by enormouspenguin** [comment]
Okay, got it. Though, it will be great if this little bump is fixed. Anyway, thanks so much for the help. I think it's time to close this.
