### ISSUE TITLE
Recently added bower.json file causes adverse effects in automated builds

### ISSUE THREAD

**Issue by tghamm** [olado/doT#209]
I currently use `doT`as a dependency for another project we use, `jQuery-QueryBuilder`.  As part of our build process, we use `wiredp`, which looks to the "main" entry in the bower.json file to determine which files to include as a part of the build.

The newly included bower.json file appears to specify `index.js` as the file to include, which is Node based, not client side JS based.  As a result, `wiredp` now includes the `index.js` file in the build pipeline, which subsequently causes failures because the `doT.js` file is the client version, not `index.js`.

This can, and indeed has been overriden in the `wiredp` configuration to properly include the `doT.js` file, so there is a workaround.

That said, I thought it prudent to bring it to the attention of the maintainers of this project.  Let me know if there is any additional useful information I can provide.

**Comment by epoberezkin** [comment]
@tghamm I suspected it my need to be doT.js... Will fix

**Comment by tghamm** [comment]
@epoberezkin, great, thanks!

**Comment by epoberezkin** [comment]
changed
