### ISSUE TITLE
remove minified file from repo

### ISSUE THREAD

**Issue by epoberezkin** [olado/doT#210]
Instead make it a part of npm prepublish script so it is available in repo (in version 2.0.0 not to brake users who depend on it)

The motivations are:
- users won't have to remember to include it in PRs
- doT is rarely used as a standalone bundle because of its tiny size, it's usually bundled into app bundle
- npm users will have minified file anyway

Bower users will have to create it as part of their build process. Given than bower downloads are 0.1% of npm downloads we can ignore this issue

@olado any objections?

**Comment by silkster** [comment]
+1

**Comment by epoberezkin** [comment]
in 2.0.0-beta.0

**Comment by cekvenich** [comment]
This is ridiculous. Most users load it from the CDN in a normal web page. So respect the happy path. If you want to pack, pack, but that is your burden. I get this from js deliver. Why force people to self host.  It does not compute.

**Comment by epoberezkin** [comment]
@cekvenich Most users use npm, webpack and bundle all libraries together with the application code. If you do want to experiment in the browser you can do it with unminified doT.js - it has no dependencies and only has 140 lines
