### ISSUE TITLE
Is it possible to expose variables without having to reference the "=it" varname?

### ISSUE THREAD

**Issue by 1mike12** [olado/doT#214]
I know we can change the varname to another string, but coming from other template engines like angular or Laravel's blade, the variables are not tied to a global `it` variable. They exist on the top level scope. 

For instance, I want to do this in dot:

### bundle
```javascript
myBundle = {param1: "hello", param2: 42, param3: "salut"};
```
### Template
```html
<div>{{param1}}</div>
<div>{{param2}}</div>
<div>{{param3}}</div>
``` 

Is this at all possible? I know it's not a huge deal to type `=it` everywhere, but it trips me up all the time because the other engines I use don't behave like this.

**Comment by epoberezkin** [comment]
The local variables can be used inside template - that's the reason not to use property names without object. Those local variable names are used for iteration, e.g., and can be used for anything. There was an attempt to remove it in the fork: https://github.com/houd1ni/doT/commit/67da310dc984abfa9688f959ffb8a6846c00f699

But it breaks iteration. A more comprehensive attempt would require parsing JavaScript in template and differentiating between local variables and properties of it. It would destroy the main advantage of doT - it's small size. It also would make it difficult to differentiate between it properties and local variables in any even moderately complex template.

**Comment by 1mike12** [comment]
thanks, appreciate the explanation. Would it be helpful to add something relating to this to the readme? I'm sure I'm not the only one to have this thought

**Comment by epoberezkin** [comment]
yep, probably. There are quite a few other things to add too. #205
