### ISSUE TITLE
Undefined object variable in for loop

### ISSUE THREAD

**Issue by LukeNZ** [olado/doT#215]
Why does this code produce the following error:

> `return def.formattedUTCTime(status). ReferenceError: status is not defined.`

Code:
 
    // statuses = []
    {{ for (var status in it.statuses) { }}
    | {{#def.formattedUTCTime(status)}} | {{#def.relativeTime(status)}} | {{=status.text}} |
    {{ } }}

I would expect `status` to be defined where it is used as a method parameter.

**Comment by zlumer** [comment]
I'm not sure I fully understand what you're trying to achieve, but I guess you want to call the function from template and print the result. That's possible if you change `#` to `=`:
```
// statuses = []
{{ for (var status in it.statuses) { }}
| {{=def.formattedUTCTime(status)}} | {{=def.relativeTime(status)}} | {{=status.text}} |
{{ } }}
```

Partials (`#`) are resolved during *compile* time, and the `status` variable is not available until *runtime* template processing.

**Comment by epoberezkin** [comment]
@zlumer yes, thank you, closing it now

**Comment by nomi-ramzan** [comment]
Hi I am trying to call a partial like this
var it = { a: {}, b: {} }
{{##def.partial:obj #}}
{{~ Object.keys(it) :key}}
{{#def.partial:it[key]}} //Error: key is undefined
{{=def.partial:it[key]}} //SyntaxError: Unexpected token :
{{~}}
What is the correct way to call a partial in a loop ?

**Comment by epoberezkin** [comment]
I think instead of `{{#def.partial:it[key]}}` you need `{{var value = it[key];}}{{#def.partial:value}}`

**Comment by vijay09-dev** [comment]
Hi, I am trying to get the value.x.sellPrice1_SS inside a function like below, Can anyone correct this?

```
 {{##def.fntest = function() {
        function getCookieValue(a) {
           var b = document.cookie.match('(^|[^;]+)\\s*' + a + '\\s*=\\s*([^;]+)');
           return b ? b.pop() : 'checked';
         }
          var regionSelectByUser = getCookieValue("FWStoreSelectedByUser");
          var region = getCookieValue("FWRegionSelected");
          var salePrice = "", price = "";
          var sellPriceObj = {"SOUTH STATES": value.x_sellPrice1_SS ,"QLD":value.x_sellPrice2_QLD};
            return sellPriceObj.QLD;
         }
  #}}
 {{#def.fntest()}} // Uncaught ReferenceError: value is not defined
```
