### ISSUE TITLE
passing doT templateSettings to dottojs/dot-packer

### ISSUE THREAD

**Issue by dvberkel** [olado/doT#218]
First of all, I think doT is an awesome template engine. It is extremely versatile and handles my needs very well.

As a thank you note I want to contribute back. I come across an personal issue, so I am posting this issue to gauge the overall interest. I can monkey-patch my problem away, but maybe there is a broader interest

The released version of doT contains an executable `dottojs` which allows you to pre-compile templates. At the moment it does not support configuring `templateSettings`. 

**Are people interested in passing `templateSettings` to `dottojs`?**

If people are interested, I am willing and able to provide a pull-request.

**Comment by epoberezkin** [comment]
@dvberkel you mean passing as command line arguments?

**Comment by dvberkel** [comment]
In a sense yes. I was thinking of an command line option to point to a json file that has tempateSettings that gets extended with the defaults.
