### ISSUE TITLE
Replace eval

### ISSUE THREAD

**Issue by alexandreStein** [olado/doT#220]
I really like the package, it's very light, efficient. It's exactly what I need in most case.
But on one project I need to implement **CSP** without **unsafe-eval** directive.

I tried to edit the source but I'm not a **JS** hero and I didn't make it woks.

I tried with **mustache** and it works perfectly. I did not check how they do.
But, I would prefer to use **doT.js**.

Do you think it could be possible?

Thanks in advance,
Best regards.

**Comment by epoberezkin** [comment]
You can pre-compile your doT templates into JavaScript modules during build-time and then you won't have to use doT itself during run-time. No changes is necessary, it's already supported.

Mustache works because it doesn't generate code, it interprets templates, which is 10 times slower.

**Comment by alexandreStein** [comment]
OK.

I should've thought about that just by remembering myself how dot.js is designed.

Sorry about that, thanks you very much.

Le 13 février 2017 20:26:58 GMT+01:00, Evgeny Poberezkin <notifications@github.com> a écrit :
>You can pre-compile your doT templates into JavaScript modules during
>build-time and then you won't have to use doT itself during run-time.
>No changes is necessary, it's already supported.
>
>Mustache works because it doesn't generate code, it interprets
>templates, which is 10 times slower.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/olado/doT/issues/220#issuecomment-279495572

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by epoberezkin** [comment]
You're welcome
