### ISSUE TITLE
基本没看懂。。。 可以帮翻译一下么？

### ISSUE THREAD

**Issue by siburuxue** [olado/doT#223]
{{ }}	for evaluation
{{= }}	for interpolation
{{! }}	for interpolation with encoding
{{# }}	for compile-time evaluation/includes and partials
{{## #}}	for compile-time defines
{{? }}	for conditionals
{{~ }}	for array iteration

**Comment by xiechenglong** [comment]
{{ }}	用于求值(evaluation)
{{= }}	用于插值(interpolation)
{{! }}	用于编码求值
{{# }}	用于编译时求值/引入和局部模板
{{## #}}	用于编译时定义
{{? }}	条件语句
{{~ }}	数组迭代
