### ISSUE TITLE
Cannot hydrate nested objects into a template

### ISSUE THREAD

**Issue by WesTyler** [olado/doT#224]
We are using doT to hydrate templated objects like this (extremely contrived) example:

```js
const source = "{templatedProperty: '{{=it.otherProperty}}'}";
const context = {
    otherProperty: {
        some: 'data',
        we  : 'want'
    }
};

const template = Dot.template(source);
let output = template(context);

output = JSON.parse(output);
```

We expect `output` to end up with a value of 
```js
{
    templatedProperty: {
        {
            some: 'data',
            we  : 'want'
        }
    }
}
```

Instead, we get:
```js
{
    templatedProperty: '[object Object]'
}
```

Would you be open to a PR to fix this behavior?

**Comment by WesTyler** [comment]
You're right, adding the JSON.stringify in the template works. Thanks for the quick reply. I'll go ahead and close out.


> I believe that JSON generation is highly preferable to perform using native JSON class instead of text templates.

I agree. We've had trouble figuring out templating with native JSON though. :\

**Comment by epoberezkin** [comment]
@WesTyler you also can use JSON.stringify in template:

```javascript
{ templatedProperty: {{=JSON.stringify(it.otherProperty)}} }
```

It may be a bit overkill in simple cases, but you can use [JSONScript](https://github.com/JSONScript/jsonscript) for "JSON templating"
