### ISSUE TITLE
Can't resolve  'fs'   in  dot/index.js  30   9---22

### ISSUE THREAD

**Issue by zhhshen** [olado/doT#225]
When I  use npm to install   doT.js ,  then   I  use  the  webpack . And i  get  the  error  as  follows:

Module not found: Error: Can't resolve 'fs' in '/Users/shen/***/node_modules/dot'
@ ./~/dot/index.js 30:9-22

I  open    the  index.js  ,  the  code is:  

var fs = require("fs");
var doT = module.exports = require("./doT");

doT.process = function(options) {
	//path, destination, global, rendermodule, templateSettings
	return new InstallDots(options).compileAll();
};

I  don' t know  how to resolve this  question .

**Comment by silkster** [comment]
Is doT saved in your package.json?

**Comment by epoberezkin** [comment]
@zhhshen at the moment you need to `require(dot/doT)` from your code you use with webpack (note the case of the letters).

Maybe it's worth adding "browser" in package.json but I'm not sure what is the latest webpack-supported package.json property...

**Comment by dodas** [comment]
@epoberezkin yes, it is "browser" by default
https://webpack.js.org/configuration/resolve/#resolve-aliasfields

**Comment by ozzyogkush** [comment]
@epoberezkin can you clarify how that would work?

**Comment by epoberezkin** [comment]
see https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders

**Comment by abdelhady** [comment]
I had the issue because I was importing it like:
```js
import {doT} from 'dot';
```
but when I used the right path `dot/doT` (based on @epoberezkin 's comment) like
```js
import {doT} from 'dot/doT';
```
it worked fine

**Comment by epoberezkin** [comment]
in 1.1.2
