### ISSUE TITLE
[Node.js] How can I generate static .html files?

### ISSUE THREAD

**Issue by rngnrs** [olado/doT#229]
Hello.
I'd like to use doT to compile templates into HTML **file**, not to generate it with Express dynamically. I searched over the Internet a lot but didn't find any information about it.

I've seen [a prototype of implementation](https://github.com/ololoepepe/ololord.js/blob/develop/src/server/core/renderer.js#L206) but it's too tricky/hacky (for example, see [line 232](https://github.com/ololoepepe/ololord.js/blob/develop/src/server/core/renderer.js#L232)).

Is there the only way to insert .def/.dot to .jst templates and generate .html from them?

**Comment by epoberezkin** [comment]
@rngnrs sorry I don't understand

> How can I generate static .html files

by passing data to compiled template function.

> to compile templates into HTML file

what do you mean? Do you mean "to render HTML from template"? Templates are compiled into JavaScript functions using `const templateFunc = dot.compile(templateStr)`. You can embed them in HTML if needed. Or you can call them by passing data to them: `const html = templateFunc(data)`.

**Comment by rngnrs** [comment]
@epoberezkin Um, well. Sorry for misunderstanding these definitions.

> Do you mean "to render HTML from template"?
Yep. I want to compile templates into JS file with functions and then render HTML from it with Node's power.
If it helps, I want to cache HTML by files and refresh them by executing special function.

**Comment by epoberezkin** [comment]
@rngnrs so my answer above is correct:

```javascript
const templateFunc = dot.compile(templateStr)
const html = templateFunc(data)
```
