### ISSUE TITLE
Question regarding the possibility to manipulate parameter data inside a function

### ISSUE THREAD

**Issue by danielkoch** [olado/doT#231]
Based on that example: https://github.com/olado/doT/blob/master/examples/advancedsnippet.txt#L119-L125

```
{{##def.testFunctionWithParam = function(str) {
		return "My name is: " + str;
	}
#}}

{{##def.mytestparam: {{=it.name}} #}}
{{#def.testFunctionWithParam(def.mytestparam)}}
```

Is it possible to manipulate the passed parameter data inside the function?

**Comment by epoberezkin** [comment]
yes, it's just normal javascript. If you pass an object the change will remain.

**Comment by danielkoch** [comment]
Hi @epoberezkin. Thanks. Sounds clear. But I can't get it work for my use-case. Inside a loop I want to access a field which holds a date. The value of this date I want to manipulate with some javascript methods. Do you have an example for such a manipulation? For me everything works except the manipulation of the date value.
