### ISSUE TITLE
I cannot get dot-packer working

### ISSUE THREAD

**Issue by aldebaran798** [olado/doT#233]
When i write the command: node node_modules/dot/bin/dot-packer -s src/views -d dist/views in my project, the result in console is this:

Compiling all doT templates...
Compiling template.dot to function

But any file is created in the dist/views folder. Thank you in advance for help.

**Comment by leoyli** [comment]
you was talking about another nom module... is probably built by doT but not maintained by doT... (lol)

**Comment by epoberezkin** [comment]
closing here

**Comment by epoberezkin** [comment]
actually dottojs CLI is here in bin

**Comment by epoberezkin** [comment]
@aldebaran798 actually I don't see why it is the wrong behaviour. It's some time ago, so probably not relevant.
