### ISSUE TITLE
No message/error when referencing notexisting variables

### ISSUE THREAD

**Issue by piorot** [olado/doT#234]
Is there any way this engine informs me about the fact that I am referencing not existing variable. 
In my usage right now it inserts **undefined** no informing me about this fact.

**Comment by epoberezkin** [comment]
It undefined, not unexisting. So it inserts "undefined".

You can:

```
{{= it.var || '' }}
```

or even

```
{{= it.var || (console.log('it.var is undefined'), '') }}
```

**Comment by leoyli** [comment]
It will fail if have nesting structure such as `it.parent.child` if `it.parent` is `undefined`. And that is a JS stuff...

**Comment by epoberezkin** [comment]
yes, you have to use guards: `it.parent && it.parent.child || ''`
