### ISSUE TITLE
How to write '{{... }}' in jst's html content?

### ISSUE THREAD

**Issue by keel** [olado/doT#235]
Now I have to do this in jst:
```
{{
 var curlyWrap = function(para){
  return '\{\{'+para+'\}\}';
};
}}

<div>{{=curlyWrap('aaa')}}</div>
```
So I can get '<div>{{aaa}}</div>' in html.
I know I can use templateSettings to change the delimiters, but the project is already done and I don't want to modify so many jst files.
Is there any better way to do this? Such as {{@ }}, will out any original content to html , include  delimiters.

**Comment by epoberezkin** [comment]
I don't know any better way. It would be very difficult to parse the internal content to understand that `}}` is not the end of interpolation but a literal, so escaping is the only way.

**Comment by keel** [comment]
I checked out JSP , it use` <\% %\> `to out` <% %> `in jsp, maybe` {\{ }\}` can solve this?
