### ISSUE TITLE
When the dot template is compiled by node.js, if it contains script tags, then the label // notes would cause an error

### ISSUE THREAD

**Issue by zengleyi** [olado/doT#238]
When the dot template is compiled by node.js, if it contains script tags, then the label //notes would cause an error。
use of/ * * / there is no problem, this is because the dot is compiled into one line strings, it did not know when is the end of the note by use  / /.

**Comment by zengleyi** [comment]
My English is terrible, I wonder if other people can understand what I'm saying。

**Comment by epoberezkin** [comment]
Yes, it's been raised a couple of times. See https://github.com/olado/doT/issues/135
You also can use `strip: false` mode to preserve whitespace.
