### ISSUE TITLE
How use a file name with part of a template from another template

### ISSUE THREAD

**Issue by McRain** [olado/doT#239]
Hey. How can I use a file name with part of a template from another template?
Works correctly
`{{#def.loadfile(p)}}` 

Does not work correctly. (error: "p is not defined")
`{{var p = 'header';}}
{{#def.loadfile(p)}}`

Thank you

**Comment by leoyli** [comment]
In you case, variable `p` is not declared in the scope of partial function `def.loadfile()`, which will throw a `referenceError`.  The only way to use it is like `{{##def.p:header#}} {{#def.loadfile(def.p)}}`.

**Comment by epoberezkin** [comment]
that is correct, `def.loadTime` is a compile time macro; `var p` is a run-time variable.

**Comment by leoyli** [comment]
BTW, you can pass your `def.loadfile` function as a run-time variable, in that way, you will have that access.
