### ISSUE TITLE
[Question] Following website is not working 

### ISSUE THREAD

**Issue by msaus** [olado/doT#240]
Hello sir,

Firstly, thank you very much for making great template engine.

I guess your one is one of the best template engine.

Then, I want to tell you that following website is not working.

https://jsperf.com/dom-vs-innerhtml-based-templating/53
https://jsperf.com/dom-vs-innerhtml-based-templating/413

Therefore, I can not look at benchmark.

Do you think you can fix it up?

Best regards,

**Comment by MikeRalphson** [comment]
I've had a go at fixing up the jsperf benchmark, but it is not letting me save my edits.

I've made a start creating a jsbench [gist](http://jsbench.github.io/#772a9a0d3a641b1b4bfcc58ac03fa026) with doT only for now to show how the setup code works, if anyone feels like adding back in all the other template engines...

**Comment by msaus** [comment]
Thank you for that.
It shows me good benchmarks.
I have been looking for template engine for my project and doT.js is one of the best one I feel.
Then, when I looked at pull requests, I found label called 2.0.0.
Is new one coming soon?
