### ISSUE TITLE
Is project dead

### ISSUE THREAD

**Issue by VladShcherbin** [olado/doT#252]
Hey, I'm choosing a template engine and this one looks like a nice small one. However, the last release was in May 2017 and 2.0 beta was in February 2017.

Is this project still maintained and release of 2.0 is planned or is it better to search for alternatives?

**Comment by leoyli** [comment]
I think there are some project undergoing, I'm not sure the current status, but I'm using this with no problem.  The original author is disappeared, not sure why, but she has authorized someone to watch after her.  Just like a lot of independent open source project, it takes people spare time, and really depends on the community.

**Comment by VladShcherbin** [comment]
@leoyli considering this info and since I'm just starting, I think it's better to find a more active project to begin with. Thanks

**Comment by epoberezkin** [comment]
@leoyli It's still the smallest, the fastest and at the same time the most flexible templating engine... Constant changes don't equate being fit for a task.

**Comment by olado** [comment]
@VladShcherbin it means it is stable :) @epoberezkin thank you for taking care of it!

**Comment by VladShcherbin** [comment]
Yep, I ended up with using `dot` because other options that I tried produced weird precompiled functions or had other issues. Dot worked flawlessly from start and has great speed.

@leoyli @epoberezkin @olado thank you all :)
