### ISSUE TITLE
Is dot.js compatible with IE8?

### ISSUE THREAD

**Issue by liu18807974232** [olado/doT#255]
I am using the version of jQuery1.9, and it seems that the written template can't be resolved in the magic of IE8. Is there any explanation for IE compatibility?

**Comment by epoberezkin** [comment]
> the written template can't be resolved in the magic of IE8

can you please post a minimal failing sample that doesn't work in IE8?

**Comment by epoberezkin** [comment]
IE8 won’t be supported, in general, so closing unless there is a failing example that’s easy to fix .
