### ISSUE TITLE
Fastest?

### ISSUE THREAD

**Issue by DanielSokil** [olado/doT#261]
Welcome to https://github.com/aui/art-template

**Comment by epoberezkin** [comment]
I don't find it an appropriate behaviour in this community to use the issues of one package to promote another package, irrespective of whether your library is faster or not. Please do not do it.

It would have been appropriate to submit a link to executable benchmarks that may indeed have shown, among other things, that your library is faster and suggesting to include these benchmarks in this library documentation. But that is not what is done here.
