### ISSUE TITLE
helper function for people

### ISSUE THREAD

**Issue by cekvenich** [olado/doT#265]
You may find this helpful:

	function bind(eID, field, value) {
		let tmpl = document.getElementById(eID)
		let doIt = doT.template(tmpl.innerHTML)
		let bind = new Object()
		bind[field] = value
		let res = doIt(bind)
		tmpl.innerHTML=res
	}

That is all.

**Comment by epoberezkin** [comment]
sorry, I do not understand what problem it solves - can you please explain?
