### ISSUE TITLE
How to render array items split with a separator

### ISSUE THREAD

**Issue by IlyaKhD** [olado/doT#278]
Hi,
Assume I have a list of items `["apple", "banana", "orange"]`
How do I render this list so that its items are split with a comma?
The result should contain **no trailing comma**, e.g.
```js
const fruits = {
   "apple",
   "banana",
   "orange"
}
```

**Comment by zlumer** [comment]
That's kinda basic JS: `array.join(',')`

**Comment by zlumer** [comment]
Though if you need a more complex logic, just check whether you're iterating on a last index.
```
{{~it.array :value:index}}
"{{=value}}" {{? index < it.array.length - 1}},{{?}}
{{~}}
```

**Comment by IlyaKhD** [comment]
The `array.join()` works best for simple constructions, so a kind of last-iteration flag required.
The `:value:index` is the one I've expected to exists, thanks.

Btw, there are some more options (sharing experience):
1) applying the following regexp on a rendered template makes is possible to the backspace symbol `\b` (deletes the latest symbol)
```js
.replace(/[\s\S]{1}\x08{1}|[\s\S]{2}\x08{2}|[\s\S]{3}\x08{3}/g, "")
```
E.g. rendered `a,b,c,\b` turns to `a,b,c`

2) you can access the `out` variable of a template function:
```js
{{ out = out.slice(0, -1); }}
```
This also removes the latest n symbols.

**Comment by pke** [comment]
> ```
> {{~it.array :value:index}}
> "{{=value}}" {{? index < it.array.length - 1}},{{?}}
> {{~}}
> ```

This should be part of the documentation. Is there even a documentation? Not everybody can read the regex to deciper the syntax for the loop.
