### ISSUE TITLE
improvement: add a simple way to loop through a key/val map

### ISSUE THREAD

**Issue by gufoscuro** [olado/doT#288]
Forgive me if this is just gibberish, but I didn't find an actual simple way to go through a map, just like you do for an array. Wouldn't be possible to do something working like this?

`{{~it.request.querystring :key:val}}`
   `{{=key}} => {{=val}}`
`{{~}}`

Thanks!

**Comment by epoberezkin** [comment]
You can use plain plain JavaScript in dot and iterate maps using for-in loop. The reason not to use maps in the templates is that the order of keys is not guaranteed, and in most cases when you render a map, the order of keys is important.

**Comment by gufoscuro** [comment]
I know you can use a for-in, I just wanted to know if a "more friendly syntax" was in the roadmap. thanks for the quick turnaround btw!
