### ISSUE TITLE
isomorphic doT import with out fs dependency

### ISSUE THREAD

**Issue by damooo** [olado/doT#294]
Hello guys, thanks for doT.
presently import/requireble module is defined in `index.js` with extra dependency on `fs`, for obvious functionality. But, there is no way to import only pure doT functionality, with out `fs` dependency. this causes bundlers like `rollup`, `webpack` to include `fs` also in isomorphic bundles for browsers.

is it possible to address this?
thanks again.

**Comment by damooo** [comment]
My fault. can import `dot.doT.js`

**Comment by epoberezkin** [comment]
probably `dot/doT.js` - can be added to docs
