### ISSUE TITLE
I want to display pricing based on cookies.. in doT.js template

### ISSUE THREAD

**Issue by vijay09-dev** [olado/doT#298]
```
 {{##def.x_sellPrice1_SS: {{=value.x_sellPrice1_SS}} #}}
                        {{##def.x_sellPrice4_WA: {{=value.x_sellPrice4_WA}} #}}
                        {{##def.sellPrice1_SS: {{=value.sellPrice1_SS}} #}}
                        {{##def.sellPrice1_SSp: {{value.sellPrice1_SS}} #}}
                        {{##def.price = '' #}}
                        {{##def.salePrice = '' #}}
                        {{##def.fntest = function(str,tr,ss,ssp,aa,t,r) {
                            var region = "SOUTH STATES";
                            var sellPriceObj = {"SOUTH STATES": str};
                            var priceObj = {"SOUTH STATES": ss};
                            for (var property in sellPriceObj) { 
                                if(region == property) { 
                                    r = sellPriceObj[property];
                                } 
                            }
                            for (var property in priceObj) {
                                if(region == property) { 
                                    t = priceObj[property];
                                } 
                            }
                            console.log(r, t); 
                            if(t === r){ 
			    return '<div class="product-card__price"><small class="dynamicproductlabel">Our Price</small>'+'$'+ price.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2}) + '</div>';
                            }
                            else{
                                 return "region : " + str + tr + sellPriceObj['SOUTH STATES'] + r + ss + t;
                            }
                        }
                        #}}
                        {{#def.fntest(def.x_sellPrice1_SS,def.x_sellPrice4_WA,def.sellPrice1_SS,def.sellPrice1_SSp, "\{\{value.sellPrice1_SS\}\}" , def.price)}}
                    
```

**Comment by vijay09-dev** [comment]
Here in this object {"SOUTH STATES": product.x_sellPrice1_SS, "QLD":product.x_sellPrice2_..} 
"SOUTH STATES" and "QLD" are getting from cookies..Please see below code.. Like this I want to impletement in doT.js template..
 
if (region != "SOUTH STATES" && typeof region != "undefined" && region !== ""){
                    for (var property in sellPriceObj) {
                        if(region == property) {
                            salePrice = sellPriceObj[property];
                        } 
                    }
                    for (var property in priceObj) {
                        if(region == property) {
                            price = priceObj[property];
                        } 
					}
					if (typeof regionSelectByUser != 'undefined' && typeof regionSelectByUser != 'null' && regionSelectByUser) {
						if(price == salePrice){
							return '<div class="product-card__price"><small class="dynamicproductlabel">Our Price</small>'+'$'+ price.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2}) + '</div>';
						} else if(price < salePrice) {
							var priceHtml = '<div class="product-card__price-was-now"><div class="now"><div class="title dynamicproductlabel">Now</div><div class="price">'+ '$' + price.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})+ '</div></div>';
							priceHtml += '<div class="was"><div class="title">Was</div><div class="price">'+'$'+ salePrice.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})+ '</div></div></div>';
							return priceHtml;
							
						} else {
							return '<div class="product-card__price"><small class="dynamicproductlabel">Our Price</small>'+'$'+ price.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2}) +'</div>';
						}
					}

**Comment by epoberezkin** [comment]
You have to include cookie in some way (depending on the environment) to the data that you pass to compiled dot template. It is not in scope of this library.
