### ISSUE TITLE
Include wiki in the source folder.

### ISSUE THREAD

**Issue by LarryBattle** [olado/doT#30]
It would really helpful if you could include the wiki site, http://olado.github.com/doT/, in the source folder.
Is this possible?
Great template engine by the way.

**Comment by epoberezkin** [comment]
@LarryBattle why?

**Comment by LarryBattle** [comment]
I think it was because the wiki has more info on how to use the api.
This issue is too old, so I'm closing it.

**Comment by epoberezkin** [comment]
@LarryBattle thank you. My plan is to have the same info in the repo as on the docs site and not use wiki (which is empty apart from the link to the site).
