### ISSUE TITLE
add ability to have formatting pipe, {{=it.now|formatDate}}

### ISSUE THREAD

**Issue by venelin-mihaylov** [olado/doT#301]
I want/need to have a formatter pipe in the template, like this:

```
{{=it.now|formatDate}}
```

Which should pass the it.now value to a formatDate() function

Can you please point me, how I might be able to hack that into dot.js ?
Thank you

**Comment by epoberezkin** [comment]
Check out v2 beta - it’s has syntax `{{fmt! it.now}}` and some other good stuff - check the release notes

**Comment by epoberezkin** [comment]
So effectively old syntax for escaping HTML was extended to format data in arbitrary way (and HTML escaping is not enabled by default - it has to be added).
