### ISSUE TITLE
is dOT what they call "logic-less" ?

### ISSUE THREAD

**Issue by EntitySpaces** [olado/doT#32]
In otherwords, is it possible to embed raw javascript in a doT template?  I'm hoping the answer is no.  This post on templating engines doesn't put dOT in the logicless category

http://engineering.linkedin.com/frontend/client-side-templating-throwdown-mustache-handlebars-dustjs-and-more

My understanding of the term logic-less is that it means you cannot embed javascript in the template, ie, the template engine doesn't understand javascript which is exactly what I want.

**Comment by epoberezkin** [comment]
I think "logic-less" quality of templating engines, in general, is overrated. It may lead to the lack of separation of concerns in controller code where the view layer code (and in most cases you need some view layer code to prepare the data for rendering) gets mixed with IO etc.

doT and other templating engines that are not logic-less allow you to keep all view code inside template.

Security issue is theoretic, as long as you don't include user input in `{{}}` and only use it in interpolation it is not a problem.
