### ISSUE TITLE
Including files in templates

### ISSUE THREAD

**Issue by trevex** [olado/doT#36]
I have a few questions concerning doT used along with node.js and express.js:

i18n is working without problems along with doT, but when I wanted to separate the template in - what other
templating engine would call - "blocks", I ran into problems. As far as I am aware doT doesn't support "blocks",
but in theory it's supposed to be capable of including files.

I am rendering my templates using the usual express.js way:

```
res.render('test.html', {pageTitle:"Test"});
```

But how can I add stuff to the default defines? To do stuff similar to the advanced example, without doing this 
within a template:

```
{{#def.loadfile(...)}}
```

I am aware about the partial support, but I need to get a partial in my context first, without redefining it in every template.

Thanking you in anticipation,
Niklas Voss

**Comment by Dabnis** [comment]
I am also using dot with node express and would like to solve the following:

I store system commands in JSON string notation and would like to place these cmd's within my dot templates. Here is an example cmd in JSON string :
 cb : '{"tm" : "users","cmd": "delete_user", "params" : {"_id" : "[[=user._id]]"} } ' : this is passed to th etemplate as 'cb'.
As you can see it is designed to parse the user._id field from the User data which is also passed to the template.
placing data-cb='[[=model.cb]]' within the template results in : '{"tm" : "users","cmd": "delete_user", "params" : {"_id" : "[[=user._id]]"} } '
As you can see the [[=user._id]] part does not get parsed with the user_id field.

Have you any suggestions for a solution to my problem?

Thanks Jonathan

**Comment by epoberezkin** [comment]
@Dabnis please submit as a separate issue and clarify. I don't understand your use case.
