### ISSUE TITLE
causes error from Chrome extension

### ISSUE THREAD

**Issue by lyricat** [olado/doT#41]
Hi, thank you for awesome work! I like doT very much and I think it's the best js template library. 

In a project I use doT.js from inside a Google Chrome extension I get the following error in the console:

Uncaught Error: Code generation from strings disallowed for this context

Is there any way to get past this error?

PS: this error causes after I change the manifest_version from 1 to 2, and then doT doesn't work because  [Content Security Policy](http://code.google.com/chrome/extensions/contentSecurityPolicy.html)

**Comment by epoberezkin** [comment]
@lyricat I believe it is answered, please reopen if there is still the question
