### ISSUE TITLE
Move dot-packer to a separate npm package

### ISSUE THREAD

**Issue by acstll** [olado/doT#58]
Shouldn't the packages used in dot-packer be listed as dependencies on package.json?

These are: commander, mkdirp and uglify-js. Now listed as dev dependencies.

```
"dependencies": {
  "commander": "*",
  "uglify-js": "*",
  "mkdirp": "*"
},
"devDependencies": {
  "mocha": "*",
  "jshint": "*"
}
```

I couldn't start using dot-packer right away after installing dot via npm.
I had to run 'npm install' on the node_modules/dot folder to get these installed,
but also mocha, jshint which you don't need if you're not developing.

**Comment by VPhantom** [comment]
So what's the official solution for this? I too was hit with `Cannot find module 'mkdirp'` when trying to use the doT for the first time (from the command line). Telling my users to go into node_modules/dot/ to run npm install there isn't the cleanest solution. :) I could always make my own project depend on those, but that'd be messy as well.

**Comment by epoberezkin** [comment]
I think I have the same preference as @olado: https://github.com/olado/doT/pull/134#issuecomment-257169519

**Comment by epoberezkin** [comment]
dot-packer removed from v2
