### ISSUE TITLE
Inappropriate Partial Template Parameter Replacement

### ISSUE THREAD

**Issue by KesshoRyu** [olado/doT#59]
If you have a partial with parameters, all instances of the parameter name get replaced in the output even if they aren't surrounded with templating syntax (such as interpolate):

```
{{##def.sayhello:greeting:
<div class='greeting'>{{=greeting}}</div>
#}}

{{#def.sayhello:it.something}}
```

will produce:

```
function anonymous(it) {var out='<div class=\'it.something\'>'+(it.something)+'</div>';return out;}
```

instead of:

```
function anonymous(it) {var out='<div class=\'greeting\'>'+(it.something)+'</div>';return out;}
```

**Comment by strrchr** [comment]
```
{{##def.sayhello:greeting111:
<div class='greeting'>{{=greeting111}}</div>
#}}

{{#def.sayhello:it.something}}
```
The parameter of partial is just a simple word replacement.
So you should keep it unique in the partial content.

**Comment by epoberezkin** [comment]
I am using this "feature" a lot, it is convenient in some cases. So I am not sure we need to change it. Maybe document and explain.

**Comment by epoberezkin** [comment]
Add to doT 101 #205
