### ISSUE TITLE
Semantic delimeters as an alternative

### ISSUE THREAD

**Issue by dannyc** [olado/doT#63]
Hi,
I know you provide the option the change the delimeters to whatever we please.  But, I was struggling to get a working example together since the regex is difficult (for me at least) to swallow.  Specifically the iterate and conditional delimeters are particularly complex.
Basically, to help ease the learning curve and increase readability at the expense of longer delimeters I was trying to create more semantic aleternative
`[if, else, endif]` in place of `[?, ??, ?]`
`[loop, endloop]` in place of `~`
`use` instead of `#`
`define` instead of `##`
With the hope that it will make reading the templates easier and understandable in the absence of documentation.
Do you think you could help post an alternative?
Thank you very much in advance!

**Comment by epoberezkin** [comment]
@dannyc can this be closed?

**Comment by dannyc** [comment]
Yes. Not an actual "issue" was just a request.
