### ISSUE TITLE
else is not supported

### ISSUE THREAD

**Issue by satazor** [olado/doT#7]
else directive is not supported within a template, e.g.:

``` javascript
{{ if (typeOf(it.entity) == "null") { }}
<li class="deleted">
    <div class="name"></div>
    <div class="icon remove"></div>
    <div class="separator"></div>
</li>
{{ } }}
{{ else { }}
<li>
    <div class="name">{{= entity.name }}</div>
    <div class="icon remove"></div>
    <div class="separator"></div>
</li>
{{ } }}
```

Could not create a template function: var out='                                                        '; if (typeOf(it.entity) == "null") { out+='                            <li class="deleted">                                <div class="name"></div>                                <div class="icon remove"></div>                                <div class="separator"></div>                            </li>                            '; } out+='                            '; else { out+='                            <li>                                <div class="name">'+( entity.name )+'</div>                                <div class="icon remove"></div>                                <div class="separator"></div>                            </li>                            '; }; out+='                        ';return out;
doT.js:83Uncaught SyntaxError: Unexpected token else

**Comment by ziad-ice06** [comment]
What is syntax for && condition?

**Comment by ashique12009** [comment]
[[##def.numberMonth = function(monthStr) {

        [[ if (monthStr == "October") { ]]
          return 10;
        [[ } else { ]]
          return 0;
        [[ } ]]
        
      }
#]]
Could anyone tell me why if is unexpected here?

SyntaxError: Unexpected token if
    at new Function (<anonymous>)

Thanks
