### ISSUE TITLE
advanced templating #def. bug

### ISSUE THREAD

**Issue by asins** [olado/doT#71]
``` javascript
{{##def.snippet:param:
test {{param.t}}====
#}}

{{#def.snippet:{t:234}}} 

```

then, Template has an error: SyntaxError: Unexpected token : 

bug set is OK

``` javascript
{{#def.snippet:{t:234} }} 
```

**Comment by epoberezkin** [comment]
@asins please see https://github.com/olado/doT/issues/195#issuecomment-257175198
