### ISSUE TITLE
the question of the doT load sort

### ISSUE THREAD

**Issue by itxiongmao** [olado/doT#74]
hi ,everybody!
 when i use doT template frame in my web page,
and ,when i use some code for getting the value of the html by doT maked,
but my own code run faster than the doT code, so i can not get the value or bind event ,so ,who can help me?

**Comment by epoberezkin** [comment]
@itxiongmao closing the issue. Please reopen and clarify if it is still relevant. doT is synchronous, JavaScript is single-threaded, so I am not sure I understand the problem.
