### ISSUE TITLE
Bower repository version tags

### ISSUE THREAD

**Issue by halkon** [olado/doT#75]
Hey olado!

I'm using doT with bower to manage versions, however it seems that the doT tag that is included is only for version 0.2.0 rather than the recent 1.0.0 version.

Any chance that you can add the 1.0.0 tag to the repository?

Thanks a bunch

**Comment by epoberezkin** [comment]
@halkon doT doesn't seem to be published to bower. Probably it can be, as there is no build process.

**Comment by halkon** [comment]
@epoberezkin I know :grin: thanks though

**Comment by epoberezkin** [comment]
ok, registered now
