### ISSUE TITLE
whitespace removal problem

### ISSUE THREAD

**Issue by codekestrel** [olado/doT#76]
Can line 92 be changed to:

``` javascript
str = ("var out='" + (c.strip ? str.replace(/(^|\r|\n)\t* +| +\t*(\r|\n|$)/g,'')
```

Changing the replacement value to empty string.
In most cases is is unnecessary, but with `li` tags, space between them on new lines is always present when using new lines to create horizontal lists.

It would be nice if the whitespace stripping could fix this issue as a bonus to compression.

**Comment by epoberezkin** [comment]
it will be changed in 2.0 to completely strip trailing whitespace on each line, but stripping whitespace in the beginning of the line can change html if some tags are split between lines...
