### ISSUE TITLE
def.snippet:param:

### ISSUE THREAD

**Issue by asins** [olado/doT#82]
``` text
{{##def.snippet:param:
_{{=param.a}}param
#}}

{{#def.snippet:{a:12} }}
```

Result:
_12{a:12}

This is a bug, right should be `_12param`

**Comment by epoberezkin** [comment]
@asins please see https://github.com/olado/doT/issues/195#issuecomment-257175198
Please reopen if it is not answering the question

**Comment by epoberezkin** [comment]
Also https://github.com/olado/doT/issues/59
