### ISSUE TITLE
Pretty HTML Output

### ISSUE THREAD

**Issue by cg219** [olado/doT#85]
I'm using doT with ExpressJS. I'm curious as to whether the out put can be prettified for formatted HTML with indents, etc.

I want

<html>
    <head>
        <title>

instead of 

<html><head><title>

**Comment by epoberezkin** [comment]
Prettifying output HTML is out of scope, as doT cab be and is used not only for HTML rendering, but also for any other rendering and code generation. There are other libraries that do it.
