### ISSUE TITLE
commander is not a devDependency

### ISSUE THREAD

**Issue by jiyinyiyong** [olado/doT#86]
As it's not written dependency attribute, `commander` will not be installe from NPM. Running `dottojs` in command line will fail.
https://github.com/olado/doT/blob/master/package.json#L27

**Comment by glukki** [comment]
uhm.. up!

**Comment by jiyinyiyong** [comment]
Actiallly I alreay gave up using doT and switched my project to React..

**Comment by epoberezkin** [comment]
duplicate of #58

**Comment by epoberezkin** [comment]
@jiyinyiyong not sure how you can compare library with 40k+ loc and 150 loc...

**Comment by jiyinyiyong** [comment]
@epoberezkin I send this issue 3 yrs ago and switched it to React a year ago. Probably I will never use doT again.
